version: '3'
volumes: 
    dados: 
services: 
    db:
        image: postgres:9.6
        env_file: 
            - ./env/db.env
        volumes: 
            # Volume dos dados
            - dados:/var/lib/postgresql/data
            # Scripts
            - ./scripts:/scripts
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    frontend: 
        image: nginx:1.13
        volumes: 
            #Site
            - ./web:/usr/share/ngnix/html
        ports: 
            - 80:80

